name: 'cascadenv'
description: 'Set environment variables in cascading fashion'
inputs:
  envfile:
    description: 'file contains environment variables'
    required: true
    default: 'env'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        while :; do
          if [[ -e "${PWD}/env" ]]; then
            echo "${PWD}/env"
          fi
          if [[ ! "${PWD}" > "${GITHUB_WORKSPACE:-/}" ]]; then
            break
          fi
          cd ..
        done | LANG=C sort | xargs cat >> "${GITHUB_ENV}"
