name: 'cascadenv'
description: 'Set environment variables in cascading fashion'
inputs:
  envfile:
    description: 'file contains environment variables'
    required: true
    default: '.env'
  working-directory:
    description: 'working directory'
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENVFILE: ${{ inputs.envfile }}
      run: |
        while :; do
          if [[ -e "${PWD}/${ENVFILE}" ]]; then
            echo "${PWD}/${ENVFILE}"
          fi
          if [[ ! "${PWD}" > "${GITHUB_WORKSPACE:-/}" ]]; then
            break
          fi
          cd ..
        done | tac | xargs cat >> "${GITHUB_ENV}"
